# =============================================================================
# EDMS OCR AGENT - EXTENDED TRAINING DATA
# PART 1: DRAWING PARAMETERS (2000+ Parameters)
# Indian Railways Drawing Standards & Nomenclature
# =============================================================================

DRAWING_NUMBERING_SYSTEMS = {
    "RDSO": {
        "format": "RDSO/<DEPT>/<YEAR>/<TYPE>/<SERIAL>",
        "example": "RDSO/EL/2024/DRG/0156",
        "components": {
            "prefix": "RDSO",
            "dept_codes": {
                "EL": "Electrical",
                "EL-TL": "Electrical - Traction Locomotives",
                "EL-EMU": "Electrical - EMU",
                "EL-AC": "Electrical - AC Coaches",
                "EL-OHE": "Electrical - OHE",
                "M": "Mechanical",
                "M-C": "Mechanical - Carriage",
                "M-W": "Mechanical - Wagon",
                "M-L": "Mechanical - Locomotive",
                "S&T": "Signal & Telecommunication",
                "TM": "Track Machine",
                "B&S": "Bridges & Structures",
                "CE": "Civil Engineering",
                "WS": "Workshop",
                "PE": "Power Electronics",
            },
            "type_codes": {
                "DRG": "Drawing",
                "SPEC": "Specification",
                "GA": "General Arrangement",
                "ASSY": "Assembly",
                "DET": "Detail",
                "INST": "Installation",
                "WRG": "Wiring Diagram",
                "SCH": "Schematic",
                "P&ID": "Piping & Instrumentation",
            },
        },
    },
    "CLW": {
        "format": "CLW/<LOCO>/<SYSTEM>/<SERIAL>/<REV>",
        "example": "CLW/WAP7/TM/0234/A",
        "loco_codes": ["WAP5", "WAP7", "WAG9", "WAG12B", "WAP4", "WAG6", "WAG7"],
        "system_codes": {
            "TM": "Traction Motor",
            "MT": "Main Transformer",
            "AUX": "Auxiliary Systems",
            "CAB": "Cab & Control",
            "BOG": "Bogie",
            "BRK": "Brake System",
            "OHE": "Pantograph/OHE Interface",
            "COOL": "Cooling System",
            "CONV": "Converter/Inverter",
            "PCC": "Propulsion Control",
            "EXC": "Excitation",
            "CMP": "Compressor",
            "BAT": "Battery & Charger",
            "LTG": "Lighting",
            "VEN": "Ventilation",
            "FIR": "Fire Detection",
            "SAF": "Safety Systems",
            "INS": "Instrumentation",
        },
    },
    "DLW": {
        "format": "DLW/<LOCO>/<SUBSYSTEM>/<YEAR>/<SERIAL>",
        "example": "DLW/WDG4G/ENG/2024/0089",
        "loco_codes": ["WDG6G", "WDG4G", "WDG5", "WDP4D", "WDP4B", "WDM3A", "WDM3D"],
        "subsystem_codes": {
            "ENG": "Engine",
            "TUR": "Turbocharger",
            "FUEL": "Fuel System",
            "AIR": "Air System",
            "COOL": "Cooling System",
            "LUB": "Lubrication",
            "EXH": "Exhaust",
            "GOV": "Governor",
            "TRC": "Traction",
            "ALT": "Alternator",
            "REC": "Rectifier",
            "CAB": "Cab",
            "BOG": "Bogie",
            "BRK": "Brake",
            "CTRL": "Control",
            "AUX": "Auxiliary",
        },
    },
    "DMW": {
        "format": "DMW/<PROJECT>/<TYPE>/<SERIAL>",
        "example": "DMW/MODWDM3A/ASSY/0145",
        "project_types": ["MODWDM3A", "MODWDM2", "MODWDP1", "UPGRAD", "POH", "IOH", "CONV", "REHAB"],
    },
    "ICF": {
        "format": "ICF/<COACH>/<TYPE>/<SERIAL>",
        "example": "ICF/LHB/AC/0567",
        "coach_codes": ["LHB", "VANDE", "AMRIT", "AC3T", "SL", "GS", "CC", "GSLRD", "WGRZACN", "EOG", "POWER"],
    },
}

DRAWING_SHEET_STANDARDS = {
    "sizes": {
        "A0": {"width_mm": 1189, "height_mm": 841, "use": "Large Assembly, GA"},
        "A1": {"width_mm": 841, "height_mm": 594, "use": "Assembly, Electrical"},
        "A2": {"width_mm": 594, "height_mm": 420, "use": "Detail, Subassembly"},
        "A3": {"width_mm": 420, "height_mm": 297, "use": "Component Detail"},
        "A4": {"width_mm": 297, "height_mm": 210, "use": "Parts List, Notes"},
    },
    "title_block_fields": [
        "Drawing Number", "Title", "Scale", "Projection",
        "Designed By", "Checked By", "Approved By", "Date",
        "Revision", "Sheet", "Size", "Material",
        "Supersedes", "Superseded By", "Change Note",
    ],
    "revision_codes": ["A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "L", "M", "N"],
}

LOCOMOTIVE_COMPONENT_DRAWINGS = {
    "DIESEL_ENGINE": {
        "DL-ENG-001": "Cylinder Block Assembly",
        "DL-ENG-002": "Cylinder Head Assembly",
        "DL-ENG-003": "Piston & Connecting Rod",
        "DL-ENG-004": "Crankshaft Assembly",
        "DL-ENG-005": "Camshaft Assembly",
        "DL-ENG-006": "Valve Train Mechanism",
        "DL-ENG-007": "Engine Mounting Frame",
        "DL-ENG-008": "Flywheel Housing",
        "DL-ENG-009": "Timing Gear Train",
        "DL-ENG-010": "Engine Base Frame",
    },
    "TURBOCHARGER": {
        "DL-TUR-001": "Turbocharger Assembly",
        "DL-TUR-002": "Compressor Housing",
        "DL-TUR-003": "Turbine Housing",
        "DL-TUR-004": "Rotor Shaft Assembly",
        "DL-TUR-005": "Bearing Housing",
        "DL-TUR-006": "Compressor Wheel",
        "DL-TUR-007": "Turbine Wheel",
        "DL-TUR-008": "Oil Inlet Line",
        "DL-TUR-009": "Oil Drain Line",
        "DL-TUR-010": "Wastegate Assembly",
    },
    "FUEL_SYSTEM": {
        "DL-FUEL-001": "Fuel Tank Assembly",
        "DL-FUEL-002": "Primary Fuel Filter",
        "DL-FUEL-003": "Secondary Fuel Filter",
        "DL-FUEL-004": "Fuel Transfer Pump",
        "DL-FUEL-005": "High Pressure Fuel Pump",
        "DL-FUEL-006": "Fuel Injector Assembly",
        "DL-FUEL-007": "Fuel Rail Assembly",
        "DL-FUEL-008": "Fuel Lines & Fittings",
        "DL-FUEL-009": "Fuel Gauge Sender",
        "DL-FUEL-010": "Fuel Fill Port",
    },
    "PANTOGRAPH": {
        "EL-PAN-001": "Pantograph Assembly Complete",
        "EL-PAN-002": "Base Frame",
        "EL-PAN-003": "Lower Arm",
        "EL-PAN-004": "Upper Arm",
        "EL-PAN-005": "Collector Head",
        "EL-PAN-006": "Carbon Strip/Insert",
        "EL-PAN-007": "Horn (End Piece)",
        "EL-PAN-008": "Pan Raising Spring",
        "EL-PAN-009": "Raising Cylinder",
        "EL-PAN-010": "Lowering Cylinder",
        "EL-PAN-011": "Anti-Sway Damper",
        "EL-PAN-012": "Insulator (Base)",
        "EL-PAN-013": "Surge Arrester",
        "EL-PAN-014": "Roof Bushings",
        "EL-PAN-015": "Control Valve",
        "EL-PAN-016": "Air Reservoir",
        "EL-PAN-017": "Pneumatic Lines",
        "EL-PAN-018": "Limit Switches",
        "EL-PAN-019": "Contact Force Sensor",
        "EL-PAN-020": "Wear Indicator",
    },
    "MAIN_TRANSFORMER": {
        "EL-MT-001": "Main Transformer Assembly",
        "EL-MT-002": "Transformer Tank",
        "EL-MT-003": "Active Part (Core & Coils)",
        "EL-MT-004": "Primary Winding (25kV)",
        "EL-MT-005": "Secondary Winding",
        "EL-MT-006": "Tertiary Winding (Aux)",
        "EL-MT-007": "Core (Laminations)",
        "EL-MT-008": "Tap Changer",
        "EL-MT-009": "Conservator Tank",
        "EL-MT-010": "Buchholz Relay",
        "EL-MT-011": "Pressure Relief Device",
        "EL-MT-012": "Oil Level Gauge",
        "EL-MT-013": "Temperature Indicator (OTI/WTI)",
        "EL-MT-014": "Silica Gel Breather",
        "EL-MT-015": "Radiator Bank",
        "EL-MT-016": "Oil Pump",
        "EL-MT-017": "Cooling Fans",
        "EL-MT-018": "HV Bushing (25kV)",
        "EL-MT-019": "LV Bushings",
        "EL-MT-020": "Grounding Strap",
    },
    "TRACTION_CONVERTER": {
        "EL-CONV-001": "Converter Assembly",
        "EL-CONV-002": "IGBT Module",
        "EL-CONV-003": "Gate Driver Unit",
        "EL-CONV-004": "DC Link Capacitor",
        "EL-CONV-005": "Input Choke/Inductor",
        "EL-CONV-006": "Output Choke/Inductor",
        "EL-CONV-007": "Snubber Capacitor",
        "EL-CONV-008": "Heat Sink (Water Cooled)",
        "EL-CONV-009": "Heat Sink (Air Cooled)",
        "EL-CONV-010": "Cooling Water Pipes",
        "EL-CONV-011": "Water Pump",
        "EL-CONV-012": "De-ionizer",
        "EL-CONV-013": "Expansion Tank",
        "EL-CONV-014": "Control Board (DSP/CPLD)",
        "EL-CONV-015": "Voltage Sensor (LEM/Hall)",
        "EL-CONV-016": "Current Sensor (LEM/Hall)",
        "EL-CONV-017": "Temperature Sensor (NTC/PTC)",
        "EL-CONV-018": "Fuse",
        "EL-CONV-019": "Pre-Charge Circuit",
        "EL-CONV-020": "Brake Chopper",
    },
    "BOGIE_FRAME": {
        "BG-FR-001": "Bogie Frame Assembly",
        "BG-FR-002": "Side Frame (Left)",
        "BG-FR-003": "Side Frame (Right)",
        "BG-FR-004": "Transom",
        "BG-FR-005": "Headstock",
        "BG-FR-006": "Bolster",
        "BG-FR-007": "Center Pivot",
        "BG-FR-008": "Side Bearers",
        "BG-FR-009": "Anchor Link Bracket",
        "BG-FR-010": "Brake Hanger Bracket",
    },
    "WHEELSET": {
        "BG-WS-001": "Wheelset Assembly",
        "BG-WS-002": "Wheel Disc",
        "BG-WS-003": "Wheel Tyre",
        "BG-WS-004": "Wheel Centre",
        "BG-WS-005": "Axle",
        "BG-WS-006": "Axle Journal",
        "BG-WS-007": "Retaining Ring",
        "BG-WS-008": "Balance Weight",
        "BG-WS-009": "Wheel Seat",
        "BG-WS-010": "Gear Seat",
    },
    "BRAKE_AIR_SYSTEM": {
        "BR-AIR-001": "Main Reservoir",
        "BR-AIR-002": "Auxiliary Reservoir",
        "BR-AIR-003": "Feed Valve (A9)",
        "BR-AIR-004": "Brake Valve (Automatic)",
        "BR-AIR-005": "Independent Brake Valve",
        "BR-AIR-006": "Distributor Valve (C3W)",
        "BR-AIR-007": "Relay Valve",
        "BR-AIR-008": "Slack Adjuster",
        "BR-AIR-009": "Limiting Valve",
        "BR-AIR-010": "Check Valve",
    },
}

DRAWING_TYPES = {
    "GA": {"code": "GA", "name": "General Arrangement", "typical_scale": ["1:20", "1:25", "1:50"], "typical_size": ["A0", "A1"]},
    "ASSY": {"code": "ASSY", "name": "Assembly Drawing", "typical_scale": ["1:5", "1:10", "1:20"], "typical_size": ["A1", "A2"]},
    "DET": {"code": "DET", "name": "Detail Drawing", "typical_scale": ["1:1", "1:2", "1:5"], "typical_size": ["A2", "A3", "A4"]},
    "SCH": {"code": "SCH", "name": "Schematic Diagram", "typical_scale": "NTS", "typical_size": ["A1", "A2"]},
    "WRG": {"code": "WRG", "name": "Wiring Diagram", "typical_scale": "NTS", "typical_size": ["A1", "A2"]},
    "P&ID": {"code": "P&ID", "name": "Piping & Instrumentation", "typical_scale": "NTS", "typical_size": ["A1"]},
    "INST": {"code": "INST", "name": "Installation Drawing", "typical_scale": ["1:10", "1:20"], "typical_size": ["A1", "A2"]},
    "EXP": {"code": "EXP", "name": "Exploded View", "typical_scale": "NTS", "typical_size": ["A1", "A2"]},
    "SEC": {"code": "SEC", "name": "Section Drawing", "typical_scale": ["1:2", "1:5", "1:10"], "typical_size": ["A2", "A3"]},
    "PL": {"code": "PL", "name": "Parts List", "typical_scale": "N/A", "typical_size": ["A3", "A4"]},
}

MATERIAL_SPECIFICATIONS = {
    "STEEL": {
        "IS 2062": "Structural Steel - E250/E350",
        "IS 1875": "Carbon Steel Billets",
        "EN8": "Medium Carbon Steel (BS970 080M40)",
        "EN9": "High Carbon Steel (BS970 070M55)",
        "EN19": "Alloy Steel (BS970 709M40)",
        "EN24": "Alloy Steel (BS970 817M40)",
        "EN31": "Ball Bearing Steel (BS970 535A99)",
        "SAE1045": "Medium Carbon Steel",
        "SAE4140": "Chromium-Molybdenum Steel",
        "AISI 316": "Stainless Steel (Austenitic)",
        "AISI 304": "Stainless Steel (Austenitic)",
    },
    "CAST_IRON": {
        "IS 210": "Grey Cast Iron Grade FG200/FG260",
        "IS 1865": "Spheroidal Graphite (SG) Iron",
        "GG25": "Grey Cast Iron (DIN)",
        "GGG40": "Ductile Iron (DIN)",
    },
    "ALUMINIUM": {
        "AA6061": "Aluminium Alloy 6061-T6",
        "AA6063": "Aluminium Alloy 6063-T5",
        "AA7075": "Aluminium Alloy 7075-T6",
        "LM6": "Aluminium Casting Alloy",
        "LM25": "Aluminium Casting Alloy",
    },
    "INSULATION": {
        "NOMEX": "Aramid Paper (Class F/H)",
        "KAPTON": "Polyimide Film",
        "MICA": "Mica Sheets/Tape",
        "FR4": "Glass Epoxy Laminate",
    },
}

TOLERANCE_STANDARDS = {
    "ISO_FITS": {
        "H7": "Hole basis - Transition fit",
        "H8": "Hole basis - Clearance fit",
        "h6": "Shaft basis - Sliding fit",
        "g6": "Shaft basis - Running fit",
        "k6": "Shaft basis - Push fit",
        "p6": "Shaft basis - Press fit",
        "s6": "Shaft basis - Heavy press fit",
    },
    "GEOMETRIC_TOLERANCES": {
        "FLATNESS": "Surface flatness tolerance",
        "STRAIGHTNESS": "Axis/surface straightness",
        "CIRCULARITY": "Cross-section roundness",
        "CYLINDRICITY": "Combined roundness and straightness",
        "PERPENDICULARITY": "90 deg to datum",
        "PARALLELISM": "Parallel to datum",
        "CONCENTRICITY": "Axis alignment",
        "RUNOUT": "Surface deviation on rotation",
        "POSITION": "True position tolerance",
    },
    "SURFACE_FINISH_RA": {
        "N5": "0.4 um - Ground",
        "N6": "0.8 um - Fine ground",
        "N7": "1.6 um - Machine finish",
        "N8": "3.2 um - Turned/Milled",
        "N9": "6.3 um - Rough machined",
        "N10": "12.5 um - Cast/Forged",
    },
}

WELDING_SPECIFICATIONS = {
    "PROCESSES": {
        "SMAW": "Shielded Metal Arc Welding (Stick)",
        "GMAW": "Gas Metal Arc Welding (MIG)",
        "GTAW": "Gas Tungsten Arc Welding (TIG)",
        "SAW": "Submerged Arc Welding",
        "FCAW": "Flux Cored Arc Welding",
    },
    "WELD_TYPES": {
        "BUTT": "Butt Joint (V/U/J Groove)",
        "FILLET": "Fillet Weld",
        "LAP": "Lap Joint",
        "PLUG": "Plug Weld",
    },
    "ELECTRODE_SPECS": {
        "E7018": "Low Hydrogen, Iron Powder",
        "E6010": "Cellulosic (Deep Penetration)",
        "E308L": "Stainless Steel",
        "ER70S-6": "MIG Wire (Carbon Steel)",
    },
}
