# =============================================================================
# EDMS OCR AGENT - EXTENDED TRAINING DATA
# PART 1: DRAWING PARAMETERS (2000+ Parameters)
# Indian Railways Drawing Standards & Nomenclature
# =============================================================================

# -----------------------------------------------------------------------------
# SECTION 1.1: DRAWING NUMBERING CONVENTIONS
# -----------------------------------------------------------------------------

DRAWING_NUMBERING_SYSTEMS = {
    # RDSO Drawing Format
    "RDSO": {
        "format": "RDSO/<DEPT>/<YEAR>/<TYPE>/<NUMBER>",
        "example": "RDSO/EL/2024/DRG/0156",
        "components": {
            "prefix": "RDSO",
            "dept_codes": {
                "EL": "Electrical",
                "EL-TL": "Electrical - Traction Locomotives",
                "EL-EMU": "Electrical - EMU",
                "EL-AC": "Electrical - AC Coaches",
                "EL-OHE": "Electrical - OHE",
                "M": "Mechanical",
                "M-C": "Mechanical - Carriage",
                "M-W": "Mechanical - Wagon",
                "M-L": "Mechanical - Locomotive",
                "S&T": "Signal & Telecommunication",
                "TM": "Track Machine",
                "B&S": "Bridges & Structures",
                "CE": "Civil Engineering",
                "WS": "Workshop",
                "PE": "Power Electronics",
            },
            "type_codes": {
                "DRG": "Drawing",
                "SPEC": "Specification",
                "GA": "General Arrangement",
                "ASSY": "Assembly",
                "DET": "Detail",
                "INST": "Installation",
                "WRG": "Wiring Diagram",
                "SCH": "Schematic",
                "P&ID": "Piping & Instrumentation",
            },
        },
    },

    # CLW Drawing Format
    "CLW": {
        "format": "CLW/<LOCO>/<SYSTEM>/<NUMBER>/<REV>",
        "example": "CLW/WAP7/TM/0234/A",
        "loco_codes": ["WAP5", "WAP7", "WAG9", "WAG12B", "WAP4", "WAG6", "WAG7"],
        "system_codes": {
            "TM": "Traction Motor",
            "MT": "Main Transformer",
            "AUX": "Auxiliary Systems",
            "CAB": "Cab & Control",
            "BOG": "Bogie",
            "BRK": "Brake System",
            "OHE": "Pantograph/OHE Interface",
            "COOL": "Cooling System",
            "CONV": "Converter/Inverter",
            "PCC": "Propulsion Control",
            "EXC": "Excitation",
            "CMP": "Compressor",
            "BAT": "Battery & Charger",
            "LTG": "Lighting",
            "VEN": "Ventilation",
            "FIR": "Fire Detection",
            "SAF": "Safety Systems",
            "INS": "Instrumentation",
        },
    },

    # DLW/DLF Drawing Format
    "DLW": {
        "format": "DLW/<LOCO>/<SUBSYSTEM>/<YEAR>/<NUMBER>",
        "example": "DLW/WDG4G/ENG/2024/0089",
        "loco_codes": ["WDG6G", "WDG4G", "WDG5", "WDP4D", "WDP4B", "WDM3A", "WDM3D"],
        "subsystem_codes": {
            "ENG": "Engine",
            "TUR": "Turbocharger",
            "FUEL": "Fuel System",
            "AIR": "Air System",
            "COOL": "Cooling System",
            "LUB": "Lubrication",
            "EXH": "Exhaust",
            "GOV": "Governor",
            "TRC": "Traction",
            "ALT": "Alternator",
            "REC": "Rectifier",
            "CAB": "Cab",
            "BOG": "Bogie",
            "BRK": "Brake",
            "CTRL": "Control",
            "AUX": "Auxiliary",
        },
    },

    # DMW/PLW Drawing Format
    "DMW": {
        "format": "DMW/<PROJECT>/<TYPE>/<NUMBER>",
        "example": "DMW/MODWDM3A/ASSY/0145",
        "project_types": [
            "MODWDM3A", "MODWDM2", "MODWDP1", "UPGRAD",
            "POH", "IOH", "CONV", "REHAB",
        ],
    },

    # ICF Drawing Format
    "ICF": {
        "format": "ICF/<COACH>/<SYSTEM>/<NUMBER>",
        "example": "ICF/LHB/AC/0567",
        "coach_codes": [
            "LHB", "VANDE", "AMRIT", "AC3T", "SL", "GS", "CC",
            "GSLRD", "WGRZACN", "EOG", "POWER",
        ],
    },
}

# -----------------------------------------------------------------------------
# SECTION 1.2: DRAWING SHEET INFORMATION
# -----------------------------------------------------------------------------

DRAWING_SHEET_STANDARDS = {
    "sizes": {
        "A0": {"width_mm": 1189, "height_mm": 841, "use": "Large Assembly, GA"},
        "A1": {"width_mm": 841, "height_mm": 594, "use": "Assembly, Electrical"},
        "A2": {"width_mm": 594, "height_mm": 420, "use": "Detail, Subassembly"},
        "A3": {"width_mm": 420, "height_mm": 297, "use": "Component Detail"},
        "A4": {"width_mm": 297, "height_mm": 210, "use": "Parts List, Notes"},
    },
    "title_block_fields": [
        "Drawing Number", "Title", "Scale", "Projection",
        "Designed By", "Checked By", "Approved By", "Date",
        "Revision", "Sheet", "Size", "Material",
        "Supersedes", "Superseded By", "Change Note",
    ],
    "revision_codes": ["A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "L", "M", "N"],
}

# -----------------------------------------------------------------------------
# SECTION 1.3: LOCOMOTIVE COMPONENT DRAWINGS (1000+ Components)
# -----------------------------------------------------------------------------

LOCOMOTIVE_COMPONENT_DRAWINGS = {
    # === DIESEL LOCOMOTIVE COMPONENTS ===
    "DIESEL_ENGINE": {
        "DL-ENG-001": "Cylinder Block Assembly",
        "DL-ENG-002": "Cylinder Head Assembly",
        "DL-ENG-003": "Piston & Connecting Rod",
        "DL-ENG-004": "Crankshaft Assembly",
        "DL-ENG-005": "Camshaft Assembly",
        "DL-ENG-006": "Valve Train Mechanism",
        "DL-ENG-007": "Engine Mounting Frame",
        "DL-ENG-008": "Flywheel Housing",
        "DL-ENG-009": "Timing Gear Train",
        "DL-ENG-010": "Engine Base Frame",
        "DL-ENG-011": "Cylinder Liner",
        "DL-ENG-012": "Main Bearing Cap",
        "DL-ENG-013": "Thrust Bearing Assembly",
        "DL-ENG-014": "Oil Pan/Sump",
        "DL-ENG-015": "Vibration Damper",
        "DL-ENG-016": "Engine Cover & Shields",
        "DL-ENG-017": "Seal Retainers",
        "DL-ENG-018": "Engine Control Unit Bracket",
        "DL-ENG-019": "Starter Motor Bracket",
        "DL-ENG-020": "Alternator Mounting",
    },
    "TURBOCHARGER": {
        "DL-TUR-001": "Turbocharger Assembly",
        "DL-TUR-002": "Compressor Housing",
        "DL-TUR-003": "Turbine Housing",
        "DL-TUR-004": "Rotor Shaft Assembly",
        "DL-TUR-005": "Bearing Housing",
        "DL-TUR-006": "Compressor Wheel",
        "DL-TUR-007": "Turbine Wheel",
        "DL-TUR-008": "Oil Inlet Line",
        "DL-TUR-009": "Oil Drain Line",
        "DL-TUR-010": "Wastegate Assembly",
        "DL-TUR-011": "Actuator Bracket",
        "DL-TUR-012": "Heat Shield",
        "DL-TUR-013": "Inlet Duct",
        "DL-TUR-014": "Outlet Duct",
        "DL-TUR-015": "Intercooler Piping",
    },
    "FUEL_SYSTEM": {
        "DL-FUEL-001": "Fuel Tank Assembly",
        "DL-FUEL-002": "Primary Fuel Filter",
        "DL-FUEL-003": "Secondary Fuel Filter",
        "DL-FUEL-004": "Fuel Transfer Pump",
        "DL-FUEL-005": "High Pressure Fuel Pump",
        "DL-FUEL-006": "Fuel Injector Assembly",
        "DL-FUEL-007": "Fuel Rail Assembly",
        "DL-FUEL-008": "Fuel Lines & Fittings",
        "DL-FUEL-009": "Fuel Gauge Sender",
        "DL-FUEL-010": "Fuel Fill Port",
        "DL-FUEL-011": "Water Separator",
        "DL-FUEL-012": "Fuel Heater",
        "DL-FUEL-013": "Overflow Return Line",
        "DL-FUEL-014": "Fuel Priming Pump",
        "DL-FUEL-015": "Fuel Shutoff Valve",
    },
    "COOLING_SYSTEM_DIESEL": {
        "DL-COOL-001": "Radiator Assembly",
        "DL-COOL-002": "Radiator Core",
        "DL-COOL-003": "Fan Assembly",
        "DL-COOL-004": "Fan Drive Mechanism",
        "DL-COOL-005": "Water Pump Assembly",
        "DL-COOL-006": "Thermostat Housing",
        "DL-COOL-007": "Thermostat",
        "DL-COOL-008": "Coolant Expansion Tank",
        "DL-COOL-009": "Coolant Hoses",
        "DL-COOL-010": "Coolant Pipes",
        "DL-COOL-011": "Aftercooler",
        "DL-COOL-012": "Oil Cooler",
        "DL-COOL-013": "Transmission Oil Cooler",
        "DL-COOL-014": "Coolant Filter",
        "DL-COOL-015": "Temperature Sensor Probe",
    },
    "LUBRICATION_SYSTEM": {
        "DL-LUB-001": "Oil Pump Assembly",
        "DL-LUB-002": "Oil Filter Housing",
        "DL-LUB-003": "Oil Filter Element",
        "DL-LUB-004": "Oil Pressure Regulator",
        "DL-LUB-005": "Oil Cooler (Engine)",
        "DL-LUB-006": "Oil Pan/Sump",
        "DL-LUB-007": "Dipstick Assembly",
        "DL-LUB-008": "Oil Fill Port",
        "DL-LUB-009": "Oil Galleries",
        "DL-LUB-010": "Main Oil Line",
        "DL-LUB-011": "Piston Cooling Jets",
        "DL-LUB-012": "Oil Pressure Gauge",
        "DL-LUB-013": "Oil Temperature Sensor",
        "DL-LUB-014": "Oil Strainer",
        "DL-LUB-015": "Crankcase Ventilation",
    },
    "EXHAUST_SYSTEM": {
        "DL-EXH-001": "Exhaust Manifold",
        "DL-EXH-002": "Exhaust Elbow",
        "DL-EXH-003": "Exhaust Silencer/Muffler",
        "DL-EXH-004": "Spark Arrestor",
        "DL-EXH-005": "Rain Cap",
        "DL-EXH-006": "Exhaust Stack",
        "DL-EXH-007": "Exhaust Gaskets",
        "DL-EXH-008": "V-Band Clamps",
        "DL-EXH-009": "Flexible Bellows",
        "DL-EXH-010": "Heat Shields",
        "DL-EXH-011": "EGR Valve (if equipped)",
        "DL-EXH-012": "SCR System (if equipped)",
        "DL-EXH-013": "DPF Housing (if equipped)",
        "DL-EXH-014": "Exhaust Temperature Probes",
        "DL-EXH-015": "Exhaust Brake (if equipped)",
    },
    # === TRACTION SYSTEM (DIESEL) ===
    "TRACTION_ALTERNATOR": {
        "DL-ALT-001": "Main Alternator Assembly",
        "DL-ALT-002": "Stator Frame",
        "DL-ALT-003": "Stator Winding",
        "DL-ALT-004": "Rotor Assembly",
        "DL-ALT-005": "Rotor Winding",
        "DL-ALT-006": "Exciter Assembly",
        "DL-ALT-007": "Rotating Rectifier",
        "DL-ALT-008": "Slip Ring Assembly",
        "DL-ALT-009": "Brush Holder",
        "DL-ALT-010": "Carbon Brushes",
        "DL-ALT-011": "Bearing (Drive End)",
        "DL-ALT-012": "Bearing (Non-Drive End)",
        "DL-ALT-013": "End Shield (DE)",
        "DL-ALT-014": "End Shield (NDE)",
        "DL-ALT-015": "Cooling Fan",
        "DL-ALT-016": "Air Inlet Duct",
        "DL-ALT-017": "Terminal Box",
        "DL-ALT-018": "Cable Lugs",
        "DL-ALT-019": "Mounting Feet",
        "DL-ALT-020": "Coupling (Engine-Alt)",
    },
    "MAIN_RECTIFIER": {
        "DL-REC-001": "Rectifier Cabinet Assembly",
        "DL-REC-002": "Diode Module",
        "DL-REC-003": "Diode Heat Sink",
        "DL-REC-004": "Diode Fuses",
        "DL-REC-005": "Snubber Circuit",
        "DL-REC-006": "DC Bus Bar",
        "DL-REC-007": "Current Shunts",
        "DL-REC-008": "Voltage Transducers",
        "DL-REC-009": "Ground Fault Detector",
        "DL-REC-010": "Cooling Blower",
        "DL-REC-011": "Air Filter",
        "DL-REC-012": "Cabinet Door",
        "DL-REC-013": "Interlock Switch",
        "DL-REC-014": "Wiring Harness",
        "DL-REC-015": "Terminal Blocks",
    },
    "TRACTION_MOTOR_DIESEL": {
        "DL-TM-001": "Traction Motor Assembly",
        "DL-TM-002": "Motor Frame/Yoke",
        "DL-TM-003": "Field Poles",
        "DL-TM-004": "Field Coils",
        "DL-TM-005": "Armature Assembly",
        "DL-TM-006": "Armature Winding",
        "DL-TM-007": "Commutator",
        "DL-TM-008": "Brush Holder Assembly",
        "DL-TM-009": "Carbon Brushes",
        "DL-TM-010": "Armature Bearing (PE)",
        "DL-TM-011": "Armature Bearing (CE)",
        "DL-TM-012": "Pinion Gear",
        "DL-TM-013": "Axle Suspension Bearing",
        "DL-TM-014": "Nose Suspension",
        "DL-TM-015": "Axle-Hung Mount",
        "DL-TM-016": "Blower Motor (TM Cooling)",
        "DL-TM-017": "Air Duct (Traction Motor)",
        "DL-TM-018": "Motor Lead Cables",
        "DL-TM-019": "Flashover Protection",
        "DL-TM-020": "Speed Sensor",
    },
    # === ELECTRIC LOCOMOTIVE COMPONENTS ===
    "PANTOGRAPH": {
        "EL-PAN-001": "Pantograph Assembly Complete",
        "EL-PAN-002": "Base Frame",
        "EL-PAN-003": "Lower Arm",
        "EL-PAN-004": "Upper Arm",
        "EL-PAN-005": "Collector Head",
        "EL-PAN-006": "Carbon Strip/Insert",
        "EL-PAN-007": "Horn (End Piece)",
        "EL-PAN-008": "Pan Raising Spring",
        "EL-PAN-009": "Raising Cylinder",
        "EL-PAN-010": "Lowering Cylinder",
        "EL-PAN-011": "Anti-Sway Damper",
        "EL-PAN-012": "Insulator (Base)",
        "EL-PAN-013": "Surge Arrester",
        "EL-PAN-014": "Roof Bushings",
        "EL-PAN-015": "Control Valve",
        "EL-PAN-016": "Air Reservoir",
        "EL-PAN-017": "Pneumatic Lines",
        "EL-PAN-018": "Limit Switches",
        "EL-PAN-019": "Contact Force Sensor",
        "EL-PAN-020": "Wear Indicator",
    },
    "MAIN_TRANSFORMER": {
        "EL-MT-001": "Main Transformer Assembly",
        "EL-MT-002": "Transformer Tank",
        "EL-MT-003": "Active Part (Core & Coils)",
        "EL-MT-004": "Primary Winding (25kV)",
        "EL-MT-005": "Secondary Winding",
        "EL-MT-006": "Tertiary Winding (Aux)",
        "EL-MT-007": "Core (Laminations)",
        "EL-MT-008": "Tap Changer",
        "EL-MT-009": "Conservator Tank",
        "EL-MT-010": "Buchholz Relay",
        "EL-MT-011": "Pressure Relief Device",
        "EL-MT-012": "Oil Level Gauge",
        "EL-MT-013": "Temperature Indicator (OTI/WTI)",
        "EL-MT-014": "Silica Gel Breather",
        "EL-MT-015": "Radiator Bank",
        "EL-MT-016": "Oil Pump",
        "EL-MT-017": "Cooling Fans",
        "EL-MT-018": "HV Bushing (25kV)",
        "EL-MT-019": "LV Bushings",
        "EL-MT-020": "Grounding Strap",
    },
    "TRACTION_CONVERTER": {
        "EL-CONV-001": "Converter Assembly",
        "EL-CONV-002": "IGBT Module",
        "EL-CONV-003": "Gate Driver Unit",
        "EL-CONV-004": "DC Link Capacitor",
        "EL-CONV-005": "Input Choke/Inductor",
        "EL-CONV-006": "Output Choke/Inductor",
        "EL-CONV-007": "Snubber Capacitor",
        "EL-CONV-008": "Heat Sink (Water Cooled)",
        "EL-CONV-009": "Heat Sink (Air Cooled)",
        "EL-CONV-010": "Cooling Water Pipes",
        "EL-CONV-011": "Water Pump",
        "EL-CONV-012": "De-ionizer",
        "EL-CONV-013": "Expansion Tank",
        "EL-CONV-014": "Control Board (DSP/CPLD)",
        "EL-CONV-015": "Voltage Sensor (LEM/Hall)",
        "EL-CONV-016": "Current Sensor (LEM/Hall)",
        "EL-CONV-017": "Temperature Sensor (NTC/PTC)",
        "EL-CONV-018": "Fuse",
        "EL-CONV-019": "Pre-Charge Circuit",
        "EL-CONV-020": "Brake Chopper",
    },
    "TRACTION_MOTOR_ELECTRIC": {
        "EL-TM-001": "3-Phase AC Traction Motor Assembly",
        "EL-TM-002": "Stator Frame",
        "EL-TM-003": "Stator Core",
        "EL-TM-004": "Stator Winding",
        "EL-TM-005": "Rotor Assembly",
        "EL-TM-006": "Rotor Core",
        "EL-TM-007": "Rotor Bars (Squirrel Cage)",
        "EL-TM-008": "End Rings",
        "EL-TM-009": "Shaft",
        "EL-TM-010": "Bearing (Drive End)",
        "EL-TM-011": "Bearing (Non-Drive End)",
        "EL-TM-012": "End Shield (DE)",
        "EL-TM-013": "End Shield (NDE)",
        "EL-TM-014": "Cooling Fan",
        "EL-TM-015": "Fan Cover",
        "EL-TM-016": "Terminal Box",
        "EL-TM-017": "Speed Encoder",
        "EL-TM-018": "Temperature Sensors (Pt100)",
        "EL-TM-019": "Pinion Gear",
        "EL-TM-020": "Motor Suspension (Axle-Hung/Frame)",
    },
    # === BOGIE COMPONENTS ===
    "BOGIE_FRAME": {
        "BG-FR-001": "Bogie Frame Assembly",
        "BG-FR-002": "Side Frame (Left)",
        "BG-FR-003": "Side Frame (Right)",
        "BG-FR-004": "Transom",
        "BG-FR-005": "Headstock",
        "BG-FR-006": "Bolster",
        "BG-FR-007": "Center Pivot",
        "BG-FR-008": "Side Bearers",
        "BG-FR-009": "Anchor Link Bracket",
        "BG-FR-010": "Brake Hanger Bracket",
        "BG-FR-011": "Motor Suspension Bracket",
        "BG-FR-012": "Spring Plank",
        "BG-FR-013": "Equalizer Beam",
        "BG-FR-014": "Axle Box Guide",
        "BG-FR-015": "Sand Box Bracket",
    },
    "WHEELSET": {
        "BG-WS-001": "Wheelset Assembly",
        "BG-WS-002": "Wheel Disc",
        "BG-WS-003": "Wheel Tyre",
        "BG-WS-004": "Wheel Centre",
        "BG-WS-005": "Axle",
        "BG-WS-006": "Axle Journal",
        "BG-WS-007": "Retaining Ring",
        "BG-WS-008": "Balance Weight",
        "BG-WS-009": "Wheel Seat",
        "BG-WS-010": "Gear Seat",
    },
    "AXLE_BOX": {
        "BG-AB-001": "Axle Box Assembly",
        "BG-AB-002": "Axle Box Housing",
        "BG-AB-003": "Roller Bearing (Cartridge)",
        "BG-AB-004": "Inner Race",
        "BG-AB-005": "Outer Race",
        "BG-AB-006": "Roller",
        "BG-AB-007": "Cage/Retainer",
        "BG-AB-008": "Labyrinth Seal (Front)",
        "BG-AB-009": "Labyrinth Seal (Rear)",
        "BG-AB-010": "Grease Retainer",
        "BG-AB-011": "End Cap (Front)",
        "BG-AB-012": "End Cap (Rear)",
        "BG-AB-013": "Axle Box Guide Liner",
        "BG-AB-014": "Temperature Sensor",
        "BG-AB-015": "Speed Sensor Ring",
    },
    "PRIMARY_SUSPENSION": {
        "BG-PS-001": "Primary Spring Set",
        "BG-PS-002": "Coil Spring (Outer)",
        "BG-PS-003": "Coil Spring (Inner)",
        "BG-PS-004": "Rubber Chevron Spring",
        "BG-PS-005": "Spring Seat (Upper)",
        "BG-PS-006": "Spring Seat (Lower)",
        "BG-PS-007": "Primary Vertical Damper",
        "BG-PS-008": "Bump Stop",
        "BG-PS-009": "Rebound Stop",
        "BG-PS-010": "Spring Shim",
    },
    "SECONDARY_SUSPENSION": {
        "BG-SS-001": "Secondary Spring Set",
        "BG-SS-002": "Flexicoil Spring",
        "BG-SS-003": "Air Spring Bellows",
        "BG-SS-004": "Air Spring Surge Tank",
        "BG-SS-005": "Leveling Valve",
        "BG-SS-006": "Height Sensor",
        "BG-SS-007": "Secondary Vertical Damper",
        "BG-SS-008": "Lateral Damper",
        "BG-SS-009": "Yaw Damper",
        "BG-SS-010": "Anti-Roll Bar",
        "BG-SS-011": "Center Pin/Pivot",
        "BG-SS-012": "Traction Link (Z-Link/Panhard)",
        "BG-SS-013": "Lateral Bumper",
        "BG-SS-014": "Emergency Spring",
        "BG-SS-015": "Air Line Connector",
    },
    "GEAR_BOX": {
        "BG-GB-001": "Gear Box Assembly",
        "BG-GB-002": "Gear Case Housing",
        "BG-GB-003": "Pinion Gear",
        "BG-GB-004": "Bull Gear (Axle Gear)",
        "BG-GB-005": "Input Shaft Bearing",
        "BG-GB-006": "Output Shaft Bearing",
        "BG-GB-007": "Gear Case Cover",
        "BG-GB-008": "Shaft Seals",
        "BG-GB-009": "Breather",
        "BG-GB-010": "Oil Level Plug",
        "BG-GB-011": "Drain Plug",
        "BG-GB-012": "Flexible Coupling",
        "BG-GB-013": "Gear Case Mounting",
        "BG-GB-014": "Quill Drive (if equipped)",
        "BG-GB-015": "Gear Mesh Guard",
    },
    # === BRAKE SYSTEM ===
    "BRAKE_AIR_SYSTEM": {
        "BR-AIR-001": "Main Reservoir",
        "BR-AIR-002": "Auxiliary Reservoir",
        "BR-AIR-003": "Feed Valve (A9)",
        "BR-AIR-004": "Brake Valve (Automatic)",
        "BR-AIR-005": "Independent Brake Valve",
        "BR-AIR-006": "Distributor Valve (C3W)",
        "BR-AIR-007": "Relay Valve",
        "BR-AIR-008": "Slack Adjuster",
        "BR-AIR-009": "Limiting Valve",
        "BR-AIR-010": "Check Valve",
        "BR-AIR-011": "Isolation Cock (Angle)",
        "BR-AIR-012": "Cut-Off Angle Cock",
        "BR-AIR-013": "Brake Pipe",
        "BR-AIR-014": "Feed Pipe",
        "BR-AIR-015": "Hose Coupling",
        "BR-AIR-016": "Pressure Gauge",
        "BR-AIR-017": "Pressure Switch",
        "BR-AIR-018": "Pressure Transducer",
        "BR-AIR-019": "Air Dryer",
        "BR-AIR-020": "Moisture Separator",
    },
    "BRAKE_MECHANICAL": {
        "BR-MECH-001": "Brake Rigging Assembly",
        "BR-MECH-002": "Brake Cylinder",
        "BR-MECH-003": "Brake Lever",
        "BR-MECH-004": "Brake Beam",
        "BR-MECH-005": "Brake Head",
        "BR-MECH-006": "Brake Shoe",
        "BR-MECH-007": "Brake Block (Composite/Cast Iron)",
        "BR-MECH-008": "Brake Hanger",
        "BR-MECH-009": "Brake Pin",
        "BR-MECH-010": "Brake Shoe Key",
        "BR-MECH-011": "Slack Adjuster (Mechanical)",
        "BR-MECH-012": "Pull Rod",
        "BR-MECH-013": "Safety Hanger",
        "BR-MECH-014": "Dead Lever",
        "BR-MECH-015": "Fulcrum Bracket",
    },
    "DISC_BRAKE": {
        "BR-DISC-001": "Brake Disc",
        "BR-DISC-002": "Brake Caliper Assembly",
        "BR-DISC-003": "Brake Pad",
        "BR-DISC-004": "Pad Retainer",
        "BR-DISC-005": "Caliper Piston",
        "BR-DISC-006": "Caliper Seal",
        "BR-DISC-007": "Caliper Mounting Bracket",
        "BR-DISC-008": "Disc Mounting Hub",
        "BR-DISC-009": "Brake Unit (BCU)",
        "BR-DISC-010": "Wear Indicator",
    },
    # === CAB & CONTROLS ===
    "CAB_STRUCTURE": {
        "CAB-STR-001": "Cab Shell Assembly",
        "CAB-STR-002": "Cab Floor",
        "CAB-STR-003": "Cab Roof",
        "CAB-STR-004": "Side Wall Panel",
        "CAB-STR-005": "Front Wall Panel",
        "CAB-STR-006": "Rear Wall Panel",
        "CAB-STR-007": "Windscreen Frame",
        "CAB-STR-008": "Windscreen Glass",
        "CAB-STR-009": "Side Window Frame",
        "CAB-STR-010": "Side Window Glass",
        "CAB-STR-011": "Door Assembly",
        "CAB-STR-012": "Door Window",
        "CAB-STR-013": "Door Latch",
        "CAB-STR-014": "Door Seal",
        "CAB-STR-015": "Grab Handles",
    },
    "CAB_DESK": {
        "CAB-DSK-001": "Driver's Desk Assembly",
        "CAB-DSK-002": "Master Controller",
        "CAB-DSK-003": "Direction/Reverser Handle",
        "CAB-DSK-004": "Power Handle/Throttle",
        "CAB-DSK-005": "Dynamic Brake Handle",
        "CAB-DSK-006": "Automatic Brake Valve Handle",
        "CAB-DSK-007": "Independent Brake Valve Handle",
        "CAB-DSK-008": "Emergency Brake Plunger",
        "CAB-DSK-009": "Speedometer",
        "CAB-DSK-010": "Ammeter",
        "CAB-DSK-011": "Voltmeter",
        "CAB-DSK-012": "Brake Pipe Pressure Gauge",
        "CAB-DSK-013": "Main Reservoir Pressure Gauge",
        "CAB-DSK-014": "Warning Lights Panel",
        "CAB-DSK-015": "Horn Button",
        "CAB-DSK-016": "Headlight Switch",
        "CAB-DSK-017": "Marker Light Switch",
        "CAB-DSK-018": "Sander Switch",
        "CAB-DSK-019": "Wiper Switch",
        "CAB-DSK-020": "Dead Man's Handle/Vigilance",
    },
    "CAB_HVAC": {
        "CAB-HVAC-001": "Air Conditioning Unit",
        "CAB-HVAC-002": "Compressor (AC)",
        "CAB-HVAC-003": "Condenser",
        "CAB-HVAC-004": "Evaporator",
        "CAB-HVAC-005": "Blower",
        "CAB-HVAC-006": "Air Filter",
        "CAB-HVAC-007": "Thermostat",
        "CAB-HVAC-008": "Control Panel",
        "CAB-HVAC-009": "Duct Work",
        "CAB-HVAC-010": "Cab Heater",
    },
    # === ELECTRICAL AUXILIARIES ===
    "COMPRESSOR_ELECTRIC": {
        "AUX-CMP-001": "Compressor Assembly",
        "AUX-CMP-002": "Compressor Motor",
        "AUX-CMP-003": "Compressor Cylinder Block",
        "AUX-CMP-004": "Piston",
        "AUX-CMP-005": "Piston Ring",
        "AUX-CMP-006": "Crankshaft",
        "AUX-CMP-007": "Connecting Rod",
        "AUX-CMP-008": "Intake Valve",
        "AUX-CMP-009": "Discharge Valve",
        "AUX-CMP-010": "Cooling Fan",
        "AUX-CMP-011": "Unloader Valve",
        "AUX-CMP-012": "Governor (Pressure)",
        "AUX-CMP-013": "Safety Valve",
        "AUX-CMP-014": "Oil Level Sight Glass",
        "AUX-CMP-015": "Mounting Bracket",
    },
    "BATTERY_SYSTEM": {
        "AUX-BAT-001": "Battery Box",
        "AUX-BAT-002": "Battery Cell (VRLA/NiCd)",
        "AUX-BAT-003": "Battery Tray",
        "AUX-BAT-004": "Battery Interconnects",
        "AUX-BAT-005": "Battery Terminal Clamps",
        "AUX-BAT-006": "Battery Charger",
        "AUX-BAT-007": "Charging Contactor",
        "AUX-BAT-008": "Battery Switch",
        "AUX-BAT-009": "Battery Fuse",
        "AUX-BAT-010": "Battery Monitor Unit",
    },
    "AUXILIARY_CONVERTER": {
        "AUX-CONV-001": "Auxiliary Converter Assembly",
        "AUX-CONV-002": "Input Transformer (if AC-DC)",
        "AUX-CONV-003": "Rectifier Unit",
        "AUX-CONV-004": "Filter Capacitor",
        "AUX-CONV-005": "Inverter Unit (if DC-AC)",
        "AUX-CONV-006": "Output Filter",
        "AUX-CONV-007": "Control Board",
        "AUX-CONV-008": "Cooling Fan",
        "AUX-CONV-009": "Enclosure",
        "AUX-CONV-010": "Circuit Breakers",
    },
}

# -----------------------------------------------------------------------------
# SECTION 1.4: DRAWING TYPES & CLASSIFICATIONS
# -----------------------------------------------------------------------------

DRAWING_TYPES = {
    "GA": {
        "code": "GA",
        "name": "General Arrangement",
        "description": "Overall layout showing major components and dimensions",
        "typical_scale": ["1:20", "1:25", "1:50"],
        "typical_size": ["A0", "A1"],
    },
    "ASSY": {
        "code": "ASSY",
        "name": "Assembly Drawing",
        "description": "Shows how parts fit together",
        "typical_scale": ["1:5", "1:10", "1:20"],
        "typical_size": ["A1", "A2"],
    },
    "DET": {
        "code": "DET",
        "name": "Detail Drawing",
        "description": "Individual part with full manufacturing info",
        "typical_scale": ["1:1", "1:2", "1:5"],
        "typical_size": ["A2", "A3", "A4"],
    },
    "SCH": {
        "code": "SCH",
        "name": "Schematic Diagram",
        "description": "Functional/electrical/pneumatic circuits",
        "typical_scale": "NTS (Not to Scale)",
        "typical_size": ["A1", "A2"],
    },
    "WRG": {
        "code": "WRG",
        "name": "Wiring Diagram",
        "description": "Electrical connections and cable routing",
        "typical_scale": "NTS",
        "typical_size": ["A1", "A2"],
    },
    "P&ID": {
        "code": "P&ID",
        "name": "Piping & Instrumentation",
        "description": "Fluid systems with controls",
        "typical_scale": "NTS",
        "typical_size": ["A1"],
    },
    "INST": {
        "code": "INST",
        "name": "Installation Drawing",
        "description": "Mounting and fitment instructions",
        "typical_scale": ["1:10", "1:20"],
        "typical_size": ["A1", "A2"],
    },
    "EXP": {
        "code": "EXP",
        "name": "Exploded View",
        "description": "Disassembled view showing parts relationship",
        "typical_scale": "NTS",
        "typical_size": ["A1", "A2"],
    },
    "SEC": {
        "code": "SEC",
        "name": "Section Drawing",
        "description": "Cross-sectional views",
        "typical_scale": ["1:2", "1:5", "1:10"],
        "typical_size": ["A2", "A3"],
    },
    "ISO": {
        "code": "ISO",
        "name": "Isometric View",
        "description": "3D representation",
        "typical_scale": "NTS",
        "typical_size": ["A2", "A3"],
    },
    "PL": {
        "code": "PL",
        "name": "Parts List",
        "description": "Bill of Materials",
        "typical_scale": "N/A",
        "typical_size": ["A3", "A4"],
    },
    "SPR": {
        "code": "SPR",
        "name": "Spare Parts Drawing",
        "description": "Exploded view with spare parts identification",
        "typical_scale": "NTS",
        "typical_size": ["A1", "A2"],
    },
}

# -----------------------------------------------------------------------------
# SECTION 1.5: MATERIAL SPECIFICATIONS IN DRAWINGS
# -----------------------------------------------------------------------------

MATERIAL_SPECIFICATIONS = {
    "STEEL": {
        "IS 2062": "Structural Steel - E250/E350",
        "IS 1875": "Carbon Steel Billets",
        "IS 2041": "Cold Rolled Steel Sheets",
        "EN8": "Medium Carbon Steel (BS970 080M40)",
        "EN9": "High Carbon Steel (BS970 070M55)",
        "EN19": "Alloy Steel (BS970 709M40)",
        "EN24": "Alloy Steel (BS970 817M40)",
        "EN31": "Ball Bearing Steel (BS970 535A99)",
        "EN36": "Case Hardening Steel (BS970 655M13)",
        "EN47": "Spring Steel (Chrome Vanadium)",
        "SAE1010": "Low Carbon Steel",
        "SAE1020": "Low Carbon Steel",
        "SAE1045": "Medium Carbon Steel",
        "SAE4140": "Chromium-Molybdenum Steel",
        "SAE4340": "Nickel-Chromium-Molybdenum Steel",
        "SAE8620": "Low Alloy Steel (Carburizing)",
        "AISI 316": "Stainless Steel (Austenitic)",
        "AISI 304": "Stainless Steel (Austenitic)",
        "AISI 410": "Stainless Steel (Martensitic)",
    },
    "CAST_IRON": {
        "IS 210": "Grey Cast Iron Grade FG200/FG260",
        "IS 1865": "Spheroidal Graphite (SG) Iron",
        "IS 4771": "Austempered Ductile Iron (ADI)",
        "GG25": "Grey Cast Iron (DIN)",
        "GGG40": "Ductile Iron (DIN)",
    },
    "ALUMINIUM": {
        "IS 733": "Aluminium Wrought Alloys",
        "IS 617": "Aluminium Casting Alloys",
        "AA6061": "Aluminium Alloy 6061-T6",
        "AA6063": "Aluminium Alloy 6063-T5",
        "AA2024": "Aluminium Alloy 2024-T3",
        "AA7075": "Aluminium Alloy 7075-T6",
        "LM6": "Aluminium Casting Alloy",
        "LM25": "Aluminium Casting Alloy",
    },
    "COPPER_BRASS": {
        "IS 191": "Copper Sheets & Strips",
        "IS 410": "Brass Ingots",
        "IS 291": "Brass Sheets",
        "C10100": "Oxygen Free Copper (OFC)",
        "C11000": "Electrolytic Tough Pitch Copper",
        "C26000": "Cartridge Brass (70/30)",
        "C36000": "Free Cutting Brass",
        "PB1": "Phosphor Bronze",
        "PB2": "Phosphor Bronze",
    },
    "PLASTICS_RUBBER": {
        "PTFE": "Polytetrafluoroethylene (Teflon)",
        "PA6": "Polyamide 6 (Nylon 6)",
        "PA66": "Polyamide 66 (Nylon 66)",
        "POM": "Polyoxymethylene (Acetal/Delrin)",
        "PEEK": "Polyetheretherketone",
        "PU": "Polyurethane",
        "NBR": "Nitrile Butadiene Rubber",
        "EPDM": "Ethylene Propylene Diene Monomer",
        "SILICONE": "Silicone Rubber",
        "VITON": "Fluoroelastomer",
    },
    "INSULATION": {
        "NOMEX": "Aramid Paper (Class F/H)",
        "KAPTON": "Polyimide Film",
        "MYLAR": "Polyester Film",
        "MICA": "Mica Sheets/Tape",
        "GPO3": "Glass Polyester Laminate",
        "FR4": "Glass Epoxy Laminate",
        "VULCANIZED_FIBER": "Vulcanized Fiber Board",
    },
}

# -----------------------------------------------------------------------------
# SECTION 1.6: TOLERANCE & FINISH SPECIFICATIONS
# -----------------------------------------------------------------------------

TOLERANCE_STANDARDS = {
    "ISO_FITS": {
        "H7": "Hole basis - Transition fit",
        "H8": "Hole basis - Clearance fit",
        "h6": "Shaft basis - Sliding fit",
        "h7": "Shaft basis - Location fit",
        "g6": "Shaft basis - Running fit",
        "k6": "Shaft basis - Push fit",
        "p6": "Shaft basis - Press fit",
        "s6": "Shaft basis - Heavy press fit",
    },
    "GEOMETRIC_TOLERANCES": {
        "FLATNESS": "Surface flatness tolerance",
        "STRAIGHTNESS": "Axis/surface straightness",
        "CIRCULARITY": "Cross-section roundness",
        "CYLINDRICITY": "Combined roundness and straightness",
        "PERPENDICULARITY": "90 degree to datum",
        "PARALLELISM": "Parallel to datum",
        "CONCENTRICITY": "Axis alignment",
        "RUNOUT": "Surface deviation on rotation",
        "TOTAL_RUNOUT": "Combined runout over length",
        "POSITION": "True position tolerance",
    },
    "SURFACE_FINISH_RA": {
        "N1": "0.025 um - Mirror finish",
        "N2": "0.05 um - Super finish",
        "N3": "0.1 um - Lapped",
        "N4": "0.2 um - Honed",
        "N5": "0.4 um - Ground",
        "N6": "0.8 um - Fine ground",
        "N7": "1.6 um - Machine finish",
        "N8": "3.2 um - Turned/Milled",
        "N9": "6.3 um - Rough machined",
        "N10": "12.5 um - Cast/Forged",
    },
}

# -----------------------------------------------------------------------------
# SECTION 1.7: WELDING & JOINING SPECIFICATIONS
# -----------------------------------------------------------------------------

WELDING_SPECIFICATIONS = {
    "PROCESSES": {
        "SMAW": "Shielded Metal Arc Welding (Stick)",
        "GMAW": "Gas Metal Arc Welding (MIG)",
        "GTAW": "Gas Tungsten Arc Welding (TIG)",
        "SAW": "Submerged Arc Welding",
        "FCAW": "Flux Cored Arc Welding",
        "RSW": "Resistance Spot Welding",
        "EBW": "Electron Beam Welding",
        "LBW": "Laser Beam Welding",
    },
    "WELD_TYPES": {
        "BUTT": "Butt Joint (V/U/J Groove)",
        "FILLET": "Fillet Weld",
        "LAP": "Lap Joint",
        "PLUG": "Plug Weld",
        "SLOT": "Slot Weld",
        "SEAM": "Seam Weld",
        "SPOT": "Spot Weld",
    },
    "ELECTRODE_SPECS": {
        "E7018": "Low Hydrogen, Iron Powder",
        "E6010": "Cellulosic (Deep Penetration)",
        "E308L": "Stainless Steel",
        "E309L": "Stainless Steel (Dissimilar)",
        "ER70S-6": "MIG Wire (Carbon Steel)",
        "ER308L": "TIG Rod (Stainless)",
    },
    "PWHT": {
        "name": "Post Weld Heat Treatment",
        "types": ["Stress Relief", "Normalizing", "Annealing"],
    },
}
