# Generated by Django 5.2.12 on 2026-03-17 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pl_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('work_type', models.CharField(choices=[('TENDER_PREP', 'Tender Preparation'), ('DRAWING_PROC', 'Drawing Processing / Alteration Update'), ('SPEC_PROC', 'Specification Processing'), ('SDR', 'Shop Drawing Request (SDR) Response'), ('TECH_EVAL', 'Technical Evaluation'), ('INSP_CALL', 'Inspection Call Processing'), ('IC_PROC', 'Inspection Certificate Processing'), ('SMI_IMPL', 'SMI Implementation'), ('VDR_REVIEW', 'Vendor Drawing Review/Approval'), ('ALT_TRACK', 'Alteration Tracking'), ('PL_ENTRY', 'PL Number Data Entry'), ('CORRESPONDENCE', 'Correspondence / Letter Processing'), ('FILING', 'Document Filing & Archiving'), ('REPORT', 'Report Preparation'), ('MEETING', 'Meeting / Coordination'), ('TRAINING', 'Training'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Category',
                'verbose_name_plural': 'Work Categories',
                'db_table': 'wl_work_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('work_type', models.CharField(choices=[('TENDER_PREP', 'Tender Preparation'), ('DRAWING_PROC', 'Drawing Processing / Alteration Update'), ('SPEC_PROC', 'Specification Processing'), ('SDR', 'Shop Drawing Request (SDR) Response'), ('TECH_EVAL', 'Technical Evaluation'), ('INSP_CALL', 'Inspection Call Processing'), ('IC_PROC', 'Inspection Certificate Processing'), ('SMI_IMPL', 'SMI Implementation'), ('VDR_REVIEW', 'Vendor Drawing Review/Approval'), ('ALT_TRACK', 'Alteration Tracking'), ('PL_ENTRY', 'PL Number Data Entry'), ('CORRESPONDENCE', 'Correspondence / Letter Processing'), ('FILING', 'Document Filing & Archiving'), ('REPORT', 'Report Preparation'), ('MEETING', 'Meeting / Coordination'), ('TRAINING', 'Training'), ('OTHER', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='ROUTINE', max_length=10)),
                ('description', models.TextField(help_text='Detailed description of work performed')),
                ('reference_number', models.CharField(blank=True, db_index=True, help_text='PL No / Drawing No / Tender No / SDR No / Case No etc.', max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('effort_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric effort (hours / quantity / pages / items)', max_digits=7, null=True)),
                ('effort_unit', models.CharField(blank=True, choices=[('HRS', 'Hours'), ('QTY', 'Quantity'), ('PAGES', 'Pages'), ('ITEMS', 'Items')], default='HRS', max_length=10)),
                ('linked_drawing_number', models.CharField(blank=True, help_text='CLW/BLW/RDSO drawing number if applicable', max_length=100)),
                ('linked_case_no', models.CharField(blank=True, help_text='Tender/case number if applicable', max_length=100)),
                ('linked_sdr_no', models.CharField(blank=True, help_text='SDR number if applicable', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Verification'), ('VERIFIED', 'Verified by Supervisor'), ('RETURNED', 'Returned for Correction'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='work_ledger.workcategory')),
                ('linked_pl_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to='pl_master.plmaster', to_field='pl_number')),
                ('submitted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries_to_verify', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Entry',
                'verbose_name_plural': 'Work Entries',
                'db_table': 'wl_work_entry',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkEntryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='work_ledger/attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='work_ledger.workentry')),
            ],
            options={
                'verbose_name': 'Work Entry Attachment',
                'verbose_name_plural': 'Work Entry Attachments',
                'db_table': 'wl_entry_attachment',
            },
        ),
        migrations.CreateModel(
            name='WorkTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('work_type', models.CharField(blank=True, choices=[('TENDER_PREP', 'Tender Preparation'), ('DRAWING_PROC', 'Drawing Processing / Alteration Update'), ('SPEC_PROC', 'Specification Processing'), ('SDR', 'Shop Drawing Request (SDR) Response'), ('TECH_EVAL', 'Technical Evaluation'), ('INSP_CALL', 'Inspection Call Processing'), ('IC_PROC', 'Inspection Certificate Processing'), ('SMI_IMPL', 'SMI Implementation'), ('VDR_REVIEW', 'Vendor Drawing Review/Approval'), ('ALT_TRACK', 'Alteration Tracking'), ('PL_ENTRY', 'PL Number Data Entry'), ('CORRESPONDENCE', 'Correspondence / Letter Processing'), ('FILING', 'Document Filing & Archiving'), ('REPORT', 'Report Preparation'), ('MEETING', 'Meeting / Coordination'), ('TRAINING', 'Training'), ('OTHER', 'Other')], help_text='Leave blank for overall target', max_length=30)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('target_unit', models.CharField(choices=[('HRS', 'Hours'), ('QTY', 'Quantity'), ('PAGES', 'Pages'), ('ITEMS', 'Items')], default='ITEMS', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Target',
                'verbose_name_plural': 'Work Targets',
                'db_table': 'wl_work_target',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='WorkVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VERIFIED', 'Verified'), ('RETURNED', 'Returned for Correction'), ('APPROVED', 'Approved')], max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_verifications', to=settings.AUTH_USER_MODEL)),
                ('work_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='work_ledger.workentry')),
            ],
            options={
                'verbose_name': 'Work Verification',
                'verbose_name_plural': 'Work Verifications',
                'db_table': 'wl_work_verification',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workentry',
            index=models.Index(fields=['user', 'work_date'], name='idx_wl_user_date'),
        ),
        migrations.AddIndex(
            model_name='workentry',
            index=models.Index(fields=['user', 'status'], name='idx_wl_user_status'),
        ),
        migrations.AddIndex(
            model_name='workentry',
            index=models.Index(fields=['work_date', 'status'], name='idx_wl_date_status'),
        ),
        migrations.AddIndex(
            model_name='workentry',
            index=models.Index(fields=['reference_number'], name='idx_wl_refnum'),
        ),
    ]
