# Generated by Django 5.2.12 on 2026-03-18 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edms', '0003_add_auxiliary_models'),
        ('versioning', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pem', models.TextField(help_text='PEM-encoded X.509 certificate')),
                ('public_key_pem', models.TextField(help_text='PEM-encoded RSA public key')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('issued_by', models.CharField(blank=True, help_text='CA / Issuing authority', max_length=300)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signing_certificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dsign_certificate',
            },
        ),
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PREPARED', 'Prepared By'), ('REVIEWED', 'Reviewed By'), ('APPROVED', 'Approved By'), ('VERIFIED', 'Verified By')], default='APPROVED', max_length=20)),
                ('signature_hash', models.CharField(help_text='RSA-SHA256 signature (hex encoded)', max_length=512)),
                ('file_checksum', models.CharField(help_text='SHA-256 of the signed file at signing time', max_length=64)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('REVOKED', 'Revoked')], default='VALID', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('it_act_compliant', models.BooleanField(default=True, help_text='IT Act 2000 Section 3 compliance flag')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='edms.document')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='document_signatures', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='versioning.documentversion')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='dsign.signingcertificate')),
            ],
            options={
                'db_table': 'dsign_signature',
                'ordering': ['-signed_at'],
            },
        ),
    ]
